{{- if .Values.outpost.enabled }}
{{- if .Values.outpost.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.outpost.serviceAccount.name | default "aiostack-outpost-sa" }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.outpost.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $annotations := dict }}
  {{- with .Values.outpost.serviceAccount.annotations }}
  {{- $annotations = merge $annotations . }}
  {{- end }}
  {{- if .Values.outpost.serviceAccount.aws.iamRoleArn }}
  {{- $_ := set $annotations "eks.amazonaws.com/role-arn" .Values.outpost.serviceAccount.aws.iamRoleArn }}
  {{- end }}
  {{- if .Values.outpost.serviceAccount.gcp.serviceAccount }}
  {{- $_ := set $annotations "iam.gke.io/gcp-service-account" .Values.outpost.serviceAccount.gcp.serviceAccount }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}