{{- if .Values.commander.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: aiostack-commander
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiostack.labels" . | nindent 4 }}
    app.kubernetes.io/name: aiostack-commander
  {{- if .Values.commander.httproute.enabled }}
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    cloud.google.com/neg: '{"exposed_ports": {"{{ .Values.commander.service.port }}":{}}}'
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.commander.service.port }}
      targetPort: {{ .Values.commander.service.targetPort }}
      protocol: TCP
      name: grpc
      appProtocol: HTTP2
  selector:
    {{- include "aiostack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: aiostack-commander
{{- end }}