apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aiostack-commander-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aiostack-commander-clusterrole
subjects:
- kind: ServiceAccount
  name: aiostack-commander
  namespace: {{ .Release.Namespace }}