apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aiostack-emissary-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes"]
  verbs: ["get", "watch", "list"]
