{{- if .Values.emissary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: aiostack-emissary
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiostack.labels" . | nindent 4 }}
    app.kubernetes.io/name: aiostack-emissary
spec:
  type: {{ .Values.emissary.service.type }}
  ports:
    - port: {{ .Values.emissary.service.port }}
      targetPort: {{ .Values.emissary.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: aiostack-emissary
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}