{{- if and .Values.ui (.Values.ui.enabled | default false) }}
{{- if .Values.ui.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiostack-ui-sa
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ui.serviceAccount.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}