{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: aiostack-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiostack.labels" . | nindent 4 }}
    app.kubernetes.io/name: aiostack-postgresql
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc }}
{{- end }}