{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: aiostack-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aiostack.labels" . | nindent 4 }}
    app.kubernetes.io/name: aiostack-postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "aiostack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: aiostack-postgresql
{{- end }}