apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiostack-docs.fullname" . }}
  namespace: {{ template "application.namespace" $ }}
  labels:
    {{- include "aiostack-docs.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"3000":{}}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "aiostack-docs.selectorLabels" . | nindent 4 }}
