apiVersion: v2
name: aiostack
description: A Helm chart for AIOStack with Observer,Outpost, Commander, Emissary, PostgreSQL and ClickHouse
type: application
version: 1.0.4-alpha
appVersion: "1.0.4_alpha"
