global:
  namespace: aiostack-test

observer:
  enabled: true
  namespaceOverride: aiostack-test
  image:
    repository: public.ecr.aws/l5a6x1y4/aiostack-observer
    tag: bananav14
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  dnsPolicy: ClusterFirst
  env:
    - name: COMPANY_ID
      value: "d9525740-beb5-401a-9e35-b487f6b30adc"
    - name: CONTROLLER_URL
      value: "aiostack-commander.aiostack-test.svc.cluster.local:8085"
    - name: IS_LOCAL_ENV
      value: "false"
    - name: TRACE_SSL
      value: "true"
    - name: PROCFS_PATH
      value: "/proc"
    - name: TRACE_INTERNAL_SVC
      value: "true"
    - name: LOGS_TTL
      value: "30s"
    - name: AGGREGATOR_MAX_CONNECTIONS
      value: "10000"
    - name: FLUSHER_WORKER_POOL_SIZE
      value: "10000"
    - name: TRACE_INTERNAL_SVC_HTTP
      value: "true"
    - name: ENABLE_METRICS
      value: "true"
    - name: ENABLE_PROFILING
      value: "false"
    - name: INTERNAL_SVC_HTTP_SAMPLE_INTERVAL
      value: "0s"
    - name: CONNECTION_CHANNEL_SIZE
      value: "100"
    - name: SKIP_NAMESPACES
      value: "aurva-dataplane-staging,aurva-dataplane-uat,aurva-dataplane-prod,kube-system,aiostack-test,aiostack,monitoring,gke-mcs"
  serviceAccount:
    create: true
    name: aiostack-observer-sa
    annotations:
    labels: {}

commander:
  enabled: true
  image:
    repository: public.ecr.aws/l5a6x1y4/aiostack-commander
    tag: bananav14
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8085
    targetPort: 8085
  resources:
    requests:
      memory: "128Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  env:
    - name: COMPANY_ID
      value: "d9525740-beb5-401a-9e35-b487f6b30adc"
    - name: LOG_ENV
      value: "production"
    - name: DB_HOST
      value: "aiostack-clickhouse.aiostack-test.svc.cluster.local"
    - name: DB_USER
      value: "aurva"
    - name: DB_PASSWORD
      value: "aurvaaiostack"
    - name: DB_DATABASE
      value: "aiostack"
    - name: DB_DEFAULT_DATABASE
      value: "default"
    - name: DB_PORT
      value: "9000"
  serviceAccount:
    create: true
    name: aiostack-commander-sa
    annotations:
    labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

postgresql:
  enabled: false
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  auth:
    postgresPassword: "aurva123"
    database: "global"
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  service:
    type: ClusterIP
    port: 5432

clickhouse:
  enabled: true
  replicaCount: 1
  image:
    repository: clickhouse/clickhouse-server
    tag: "24.8-alpine"
    pullPolicy: IfNotPresent
  auth:
    username: "aurva"
    database: "aiostack_logs"
    password: "aurvaaiostack"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    size: 20Gi
  service:
    type: ClusterIP
    httpPort: 8123
    nativePort: 9000
    postgresqlPort: 9005
  config:
    logLevel: "information"
    maxMemoryUsage: 0.8
    maxServerMemoryUsage: 0.9
    timezone: "UTC"
    queryLog: false
    customSettings: |
      <merge_tree>
        <max_suspicious_broken_parts>100</max_suspicious_broken_parts>
        <parts_to_delay_insert>1000</parts_to_delay_insert>
        <parts_to_throw_insert>3000</parts_to_throw_insert>
      </merge_tree>
      <profiles>
        <default>
          <max_memory_usage>8000000000</max_memory_usage>
          <use_uncompressed_cache>0</use_uncompressed_cache>
          <load_balancing>random</load_balancing>
          <max_execution_time>300</max_execution_time>
        </default>
      </profiles>


