{{- if .Values.n8n.enabled }}
{{- if .Values.n8n.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.n8n.serviceAccount.name }}
  labels:
    {{- include "aitools.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
  {{- with .Values.n8n.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
