{{- if .Values.mindsdb.enabled }}
{{- if .Values.mindsdb.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aitools.serviceAccountName" . }}
  labels:
    {{- include "aitools.labels" . | nindent 4 }}
    app.kubernetes.io/component: mindsdb
  {{- with .Values.mindsdb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
